[package]
name = "klamath-util"
version = "0.1.0"
edition = "2018"

[dependencies]
approx = "0.4"
atty = "0.2"
clap = "2.33"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
tinyvec = { version = "1.2", features = ["alloc"] }
