# Apache 2.0 License
# 
# Rules for converting models into images. Uses blenderscript.

# PHONY: models_out

BLENDERSCRIPT = $(UTIL) blenderscript
FDIR = flats
GDIR = graphics
PDIR = patches
SDIR = sprites

MODELS_OUT = 

models_out: $(MODELS_OUT) 


